
version: "3"
services:

  sandbox:
    build: .
    command: runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
